version: '2.3'

services:
  ubuntu18.04_docker:
    image: liprin1129/mac-ubuntu18.04:opencv-code
    restart: 'no'
    privileged: true
    tty: true
    stdin_open: true
    ipc: host
    user: root
    environment:
      - DISPLAY=host.docker.internal:0
    volumes: #local:destination
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/Developments/Personal-Dev.:/Development

