FROM liprin1129/jdocker-base

#RUN apt-get update && \
#    apt-get install -y --no-install-recommends \
#    	    build-essential \
#	    qtcreator \
#    	    qt5-default \
#    	    libqt5opengl5-dev \
#    	    qt5-doc \
#    	    qt5-doc-html qtbase5-doc-html \
#    	    qtbase5-examples \
#    	    dbus

RUN apt install -y --no-install-recommends qt5-default

#RUN apt install -y --no-install-recommends dbus
#RUN dbus-uuidgen > /var/lib/dbus/machine-id

