FROM liprin1129/ubuntu18.04:cudagl10.0-cudnn7.5-opencv

RUN apt update
RUN apt install -y libeigen3-dev
RUN apt install -y --no-install-recommends libvtk7-dev
RUN apt install -y --no-install-recommends libflann-dev


