#FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04
FROM liprin1129/ubuntu16.04:cudagl-cudnn-qt5

RUN apt-get update \
    && apt-get install -y -qq --no-install-recommends apt-utils \
    && apt-get install -y -qq --no-install-recommends ca-certificates unzip wget \
    && apt-get install -y -qq --no-install-recommends build-essential cmake \
    && apt-get install -y -qq --no-install-recommends pkg-config \
    && apt-get install -y -qq --no-install-recommends libjpeg-dev libtiff5-dev libjasper-dev libpng12-dev \
    && apt-get install -y -qq --no-install-recommends ffmpeg libavresample-dev libavcodec-dev libavformat-dev libswscale-dev libxvidcore-dev libx264-dev libxine2-dev \
    && apt-get install -y -qq --no-install-recommends libv4l-dev v4l-utils \
    && apt-get install -y -qq --no-install-recommends libtbb-dev \
    && apt-get install -y -qq --no-install-recommends libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
    && apt-get install -y -qq --no-install-recommends qt5-default \
    && apt-get install -y -qq --no-install-recommends mesa-utils libgl1-mesa-dri libqt5opengl5-dev \
    && apt-get install -y -qq --no-install-recommends libatlas-base-dev gfortran libeigen3-dev \
    && apt-get install -y -qq --no-install-recommends python3-dev python3-pip python3-setuptools

RUN mkdir /tmp/opencv \
    && cd /tmp/opencv \
    && wget -O opencv.zip https://github.com/opencv/opencv/archive/3.4.0.zip \
    && unzip opencv.zip \
    && wget -O opencv_contrib.zip https://github.com/opencv/opencv_contrib/archive/3.4.0.zip \
    && unzip opencv_contrib.zip \
    && cd opencv-3.4.0 \
    && mkdir build \
    && cd build \
    && cmake -D CMAKE_BUILD_TYPE=RELEASE \
       	   	 -D CMAKE_INSTALL_PREFIX=/usr/local \
	         -D WITH_TBB=ON \
		 -D WITH_IPP=OFF \
      		 -D WITH_1394=OFF \
      		 -D BUILD_WITH_DEBUG_INFO=OFF \
      		 -D BUILD_DOCS=OFF \
      		 -D INSTALL_C_EXAMPLES=ON \
      		 -D INSTALL_PYTHON_EXAMPLES=ON \
      		 -D BUILD_EXAMPLES=ON \
      		 -D BUILD_TESTS=OFF \
      		 -D BUILD_PERF_TESTS=OFF \
      		 -D WITH_QT=ON \
      		 -D WITH_OPENGL=ON \
      		 -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-3.4.0/modules \
		 #-D BUILD_opencv_python2=ON \
		 #-D BUILD_opencv_python3=ON \
      		 -D WITH_V4L=ON  \
      		 -D WITH_FFMPEG=ON \
      		 -D WITH_XINE=ON \
      		 #-D BUILD_NEW_PYTHON_SUPPORT=ON \
      		 -D WITH_CUBLAS=ON \
      		 -D WITH_NVCUVID=ON \
      		 -D ENABLE_FAST_MATH=ON \
      		 -D WITH_CUDA=ON \
      		 -D CUDA_FAST_MATH=ON \
      		 -D CUDA_ARCH_BIN="6.1" \
      		 -D CUDA_ARCH_PTX="6.1" \
      		 ../ | tee /tmp/opencv_cmake.log \
	&& make -j "$(nproc)" \
	&& make install \
	&& sh -c 'echo '/usr/local/lib' > /etc/ld.so.conf.d/opencv.conf' \
	&& ldconfig \
	&& cd /tmp \
	&& rm -rf opencv


#mkdir opencv-3.3.0/build && cd opencv-3.3.0/build
#cmake -G "Unix Makefiles" --build . -D BUILD_CUDA_STUBS=OFF -D BUILD_DOCS=OFF \
#-D BUILD_EXAMPLES=OFF -D BUILD_JASPER=OFF -D BUILD_JPEG=OFF -D BUILD_OPENEXR=OFF \
#-D BUILD_PACKAGE=ON -D BUILD_PERF_TESTS=OFF -D BUILD_PNG=OFF -D BUILD_SHARED_LIBS=ON \
#-D BUILD_TBB=OFF -D BUILD_TESTS=OFF -D BUILD_TIFF=OFF -D BUILD_WITH_DEBUG_INFO=ON \
#-D BUILD_ZLIB=OFF -D BUILD_WEBP=OFF -D BUILD_opencv_apps=ON -D BUILD_opencv_calib3d=ON \
#-D BUILD_opencv_core=ON -D BUILD_opencv_cudaarithm=OFF -D BUILD_opencv_cudabgsegm=OFF \
#-D BUILD_opencv_cudacodec=OFF -D BUILD_opencv_cudafeatures2d=OFF -D BUILD_opencv_cudafilters=OFF \
#-D BUILD_opencv_cudaimgproc=OFF -D BUILD_opencv_cudalegacy=OFF -D BUILD_opencv_cudaobjdetect=OFF \
#-D BUILD_opencv_cudaoptflow=OFF -D BUILD_opencv_cudastereo=OFF -D BUILD_opencv_cudawarping=OFF \
#-D BUILD_opencv_cudev=OFF -D BUILD_opencv_features2d=ON -D BUILD_opencv_flann=ON \
#-D BUILD_opencv_highgui=ON -D BUILD_opencv_imgcodecs=ON -D BUILD_opencv_imgproc=ON \
#-D BUILD_opencv_java=OFF -D BUILD_opencv_ml=ON -D BUILD_opencv_objdetect=ON \
#-D BUILD_opencv_photo=ON -D BUILD_opencv_python2=OFF -D BUILD_opencv_python3=ON \
#-D BUILD_opencv_shape=ON -D BUILD_opencv_stitching=ON -D BUILD_opencv_superres=ON \
#-D BUILD_opencv_ts=ON -D BUILD_opencv_video=ON -D BUILD_opencv_videoio=ON \
#-D BUILD_opencv_videostab=ON -D BUILD_opencv_viz=OFF -D BUILD_opencv_world=OFF \
#-D CMAKE_BUILD_TYPE=RELEASE -D WITH_1394=ON -D WITH_CUBLAS=OFF -D WITH_CUDA=OFF \
#-D WITH_CUFFT=OFF -D WITH_EIGEN=ON -D WITH_FFMPEG=ON -D WITH_GDAL=OFF -D WITH_GPHOTO2=OFF \
#-D WITH_GIGEAPI=ON -D WITH_GSTREAMER=OFF -D WITH_GTK=ON -D WITH_INTELPERC=OFF -D WITH_IPP=ON \
#-D WITH_IPP_A=OFF -D WITH_JASPER=ON -D WITH_JPEG=ON -D WITH_LIBV4L=ON -D WITH_OPENCL=ON \
#-D WITH_OPENCLAMDBLAS=OFF -D WITH_OPENCLAMDFFT=OFF -D WITH_OPENCL_SVM=OFF -D WITH_OPENEXR=ON \
#-D WITH_OPENGL=ON -D WITH_OPENMP=OFF -D WITH_OPENNI=OFF -D WITH_PNG=ON -D WITH_PTHREADS_PF=OFF \
#-D WITH_PVAPI=OFF -D WITH_QT=ON -D WITH_TBB=ON -D WITH_TIFF=ON -D WITH_UNICAP=OFF \
#-D WITH_V4L=OFF -D WITH_VTK=OFF -D WITH_WEBP=ON -D WITH_XIMEA=OFF -D WITH_XINE=OFF \
#-D WITH_LAPACKE=ON -D WITH_MATLAB=OFF ..
