FROM ubuntu16.04:cudagl

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    qtcreator \
    qt5-default \
    libqt5opengl5-dev \
    qt5-doc \
    qt5-doc-html qtbase5-doc-html \
    qtbase5-examples
